-- PinMap v3
-- รันไฟล์นี้ใน Supabase SQL Editor หลังจาก backup/ตรวจข้อมูลเดิม
-- ระบบนี้ใช้ Supabase Auth + RLS จริง:
-- 1) ผู้ใช้ต้อง login ด้วย email/password
-- 2) เข้าห้องครั้งแรกด้วยรหัสห้อง
-- 3) สมาชิกห้องถูกผูกกับ auth.users
-- 4) ครั้งต่อไปกดห้องที่บันทึกไว้ได้โดยไม่ต้องกรอกรหัสใหม่

create extension if not exists pgcrypto;

create table if not exists public.pins (
  id bigint generated by default as identity primary key,
  room text not null,
  lat double precision not null,
  lng double precision not null,
  title text not null default 'จุดใหม่',
  address text not null default '',
  note text not null default '',
  created_by text not null default 'ผู้ใช้',
  created_by_user_id uuid,
  color text not null default '#ef4444',
  icon text not null default 'pin',
  icon_img text not null default '',
  created_at timestamptz not null default now()
);
alter table public.pins add column if not exists address text not null default '';
alter table public.pins add column if not exists color text not null default '#ef4444';
alter table public.pins add column if not exists icon text not null default 'pin';
alter table public.pins add column if not exists icon_img text not null default '';
alter table public.pins add column if not exists created_by_user_id uuid;
create index if not exists pins_room_created_idx on public.pins(room,created_at);

create table if not exists public.rooms (
  room text primary key,
  passcode_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.room_members (
  user_id uuid not null references auth.users(id) on delete cascade,
  room text not null references public.rooms(room) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key(user_id,room)
);
create index if not exists room_members_room_idx on public.room_members(room);

create table if not exists public.saved_rooms (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  room text not null references public.rooms(room) on delete cascade,
  label text not null default '',
  created_at timestamptz not null default now(),
  unique(user_id,room)
);

alter table public.rooms enable row level security;
alter table public.room_members enable row level security;
alter table public.saved_rooms enable row level security;
alter table public.pins enable row level security;

-- ไม่เปิดให้ client อ่าน rooms/room_members ตรงๆ
drop policy if exists "rooms_no_direct_select" on public.rooms;
drop policy if exists "members_self_select" on public.room_members;
drop policy if exists "saved_rooms_select" on public.saved_rooms;
drop policy if exists "saved_rooms_insert" on public.saved_rooms;
drop policy if exists "saved_rooms_update" on public.saved_rooms;
drop policy if exists "saved_rooms_delete" on public.saved_rooms;

create policy "members_self_select" on public.room_members
for select to authenticated using (user_id=auth.uid());

create policy "saved_rooms_select" on public.saved_rooms
for select to authenticated using (user_id=auth.uid());
create policy "saved_rooms_insert" on public.saved_rooms
for insert to authenticated with check (user_id=auth.uid());
create policy "saved_rooms_update" on public.saved_rooms
for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "saved_rooms_delete" on public.saved_rooms
for delete to authenticated using (user_id=auth.uid());

-- Join ห้องครั้งแรก / ตรวจรหัสห้อง
create or replace function public.room_join(p_room text,p_passcode text)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare existing_hash text;
begin
  if auth.uid() is null then return false; end if;
  if trim(coalesce(p_room,''))='' or coalesce(p_passcode,'')='' then return false; end if;

  insert into public.rooms(room,passcode_hash)
  values(trim(p_room),crypt(p_passcode,gen_salt('bf')))
  on conflict(room) do nothing;

  select passcode_hash into existing_hash from public.rooms where room=trim(p_room);
  if existing_hash is null or existing_hash <> crypt(p_passcode,existing_hash) then
    return false;
  end if;

  insert into public.room_members(user_id,room)
  values(auth.uid(),trim(p_room))
  on conflict(user_id,room) do nothing;
  return true;
end;
$$;
grant execute on function public.room_join(text,text) to authenticated;

-- เข้าห้องที่เคยเป็นสมาชิกแล้ว โดยไม่ต้องเก็บรหัสผ่านไว้ใน browser/database
create or replace function public.room_enter_saved(p_room text)
returns boolean
language sql
security definer
set search_path=public
as $$
  select exists(
    select 1 from public.room_members
    where user_id=auth.uid() and room=trim(p_room)
  );
$$;
grant execute on function public.room_enter_saved(text) to authenticated;

drop policy if exists "pinmap_read" on public.pins;
drop policy if exists "pinmap_insert" on public.pins;
drop policy if exists "pinmap_update" on public.pins;
drop policy if exists "pinmap_delete" on public.pins;

create policy "pinmap_read" on public.pins
for select to authenticated
using (exists(select 1 from public.room_members m where m.user_id=auth.uid() and m.room=pins.room));

create policy "pinmap_insert" on public.pins
for insert to authenticated
with check (exists(select 1 from public.room_members m where m.user_id=auth.uid() and m.room=pins.room));

create policy "pinmap_update" on public.pins
for update to authenticated
using (exists(select 1 from public.room_members m where m.user_id=auth.uid() and m.room=pins.room))
with check (exists(select 1 from public.room_members m where m.user_id=auth.uid() and m.room=pins.room));

create policy "pinmap_delete" on public.pins
for delete to authenticated
using (exists(select 1 from public.room_members m where m.user_id=auth.uid() and m.room=pins.room));

-- Realtime
do $$
begin
  alter publication supabase_realtime add table public.pins;
exception when duplicate_object then null;
end $$;

-- หมายเหตุ:
-- Supabase Dashboard > Authentication > Providers > Email
-- เปิด Email provider และกำหนดว่าจะบังคับ email confirmation หรือไม่
-- ถ้าบังคับ confirmation ผู้ใช้ต้องกดยืนยันในอีเมลก่อน login ครั้งแรก
